POST {{local}}/api/v1/board
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "title": "신고요",
  "content": "이것좀 봐주세요",
  "petitionUrl": "www1.president.go.kr/petitions/6004"
}

### 게시글 수정
POST {{local}}/api/v1/board/update
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "boardId": 1,
  "title": "신고요 수정",
  "content": "이것좀 봐주세요 수정"
}

### 게시글 불러오기
GET {{local}}/api/v1/getBoard/1
Content-Type: application/json

### 게시글 리스트 불러오기
GET {{local}}/api/v1/getBoard/list?search=&size=2
Content-Type: application/json

### 게시글 리스트 불러오기 조회순
GET {{local}}/api/v1/getBoard/list?search=&page=0&size=3&sort=viewCounts
Content-Type: application/json

### 게시글 찬성/반대
POST {{local}}/api/v1/board/like
Content-Type: application/json
Authorization: Bearer {{TOKEN}}

{
  "boardId": 1,
  "boardState": "LIKE"
}

###
GET {{local}}/test-token

> {%
client.global.set('TOKEN', response.body.data.token)
client.log(client.global.get('TOKEN'));
 %}

