POST {{local}}/api/v1/board
Content-Type: application/json

{
  "petitionId": "600413",
  "title": "신고요",
  "content": "이것좀 봐주세요",
  "memberId": 1
}

### 게시글 수정
POST {{local}}/api/v1/board/update
Content-Type: application/json

{
  "boardId": 1,
  "title": "신고요 수정",
  "content": "이것좀 봐주세요 수정"
}

### 게시글 불러오기
GET {{local}}/api/v1/board/1
Content-Type: application/json