POST {{local}}/api/v1/board
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjMyMzg4OTQ0LCJleHAiOjE2MzIzODk1NDR9.Ju5xSV4zJ5c5f0zDFpE_5Vo7D8K-DtSzEXkPHp01LfA

{
  "petitionId": "600413",
  "title": "신고요",
  "content": "이것좀 봐주세요"
}

### 게시글 수정
POST {{local}}/api/v1/board/update
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjMyMzg4OTQ0LCJleHAiOjE2MzIzODk1NDR9.Ju5xSV4zJ5c5f0zDFpE_5Vo7D8K-DtSzEXkPHp01LfA

{
  "boardId": 1,
  "title": "신고요 수정",
  "content": "이것좀 봐주세요 수정"
}

### 게시글 불러오기
GET {{local}}/api/v1/board/1
Content-Type: application/json

### 게시글 리스트 불러오기
GET {{local}}/api/v1/board/list?search=&page=0
Content-Type: application/json

### 게시글 찬성/반대
POST {{local}}/api/v1/board/like
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiaWF0IjoxNjMyNDY4OTIyLCJleHAiOjE2MzI0Njk1MjJ9.jKnXILgCxST05CjY4x0HTO0Di7W08kPxNRENZDrqWZQ

{
  "boardId": 1,
  "boardState": "LIKE"
}